### ISSUE TITLE
Competitive companion parser error

### ISSUE THREAD

**Issue by darkshadow013** [cpeditor/cpeditor#345] opened 2020-05-13 10:10 UTC
While parsing problems from competitve companion a JSON parser error reflects. It resolves on restart cp editor. But it is irritating.
![Screenshot from 2020-05-13 15-39-32](https://user-images.githubusercontent.com/41981066/81800148-fdaa0100-952f-11ea-9c4a-b2a87ac99648.png)

 - OS: Ubuntu 18.04
 - CP Editor Version: 6.2.5

**Comment by coder3101** [comment] 2020-05-13 11:15
Upload the log files. Options->Show Log file and upload the selected file here!

Reproduce this and upload the log file of that session.

**Comment by ouuan** [comment] 2020-05-13 11:47
In short, you provided nearly no information. It's just like saying "I've got a compilation error, do you know why?".

At least, you should provide the link to the problem, and it will be better if you can provide the log file (Options->Show Log Files).

You said "It resolves on restart cp editor", so it seems that you can't reproduce it. So the question is, how often does this happen? If it rarely happens:
1. If you didn't gather enough information when the error happened, it will be nearly impossible to find the reason of the bug.
2. It doesn't hurt much.

I'll close this in 24 hours if you don't provide more information.

**Comment by darkshadow013** [comment] 2020-05-13 11:52
> Upload the log files. Options->Show Log file and upload the selected file here!
> 
> Reproduce this and upload the log file of that session.

[cpeditor-2020-05-12-17-37-48-725-0.log](https://github.com/cpeditor/cpeditor/files/4621755/cpeditor-2020-05-12-17-37-48-725-0.log)

**Comment by coder3101** [comment] 2020-05-13 12:01
```
[2020-05-13T15:31:25.784][INFO][companionServer/onReadReady] Truncated request is : 
POST / HTTP/1.1
Host: localhost:10045
Connection: keep-alive
Content-Length: 435
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Content-Type: application/json
Accept: */*
Origin: chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl
Sec-Fetch-Site: none
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,hi;q=0.7
Cookie: _xsrf=2|abc9fbc4|6d08c5a5dc80b26e755aae54ae70c4b7|1588235979; username-localhost-8890="2|1:0|10:1588244089|23:username-localhost-8890|44:ZjVjMGNkZDY0MDM3NDgyYWJjNzA5MWUyMmM0MTUzMjE=|8e3cc8d82e6711b64123672865a7ced361f69befac8620fe5797c8783e965454"; username-localhost-8891="2|1:0|10:1588244967|23:username-localhost-8891|44:ZjkxYWRkMzIzYmVjNDlhNDlmNGY4ZTFiYmM0YmUyNTk=|f141afcdd2792c0adde23e75ca88bd7a1773e000ddce076752147d807f6efd20"; username-localhost-8892="2|1:0|10:1588244994|23:username-localhost-8892|44:MjA0MTc5OWFlYzZjNDFmMDhkZmRkMzMwZjY1ZjU5NmY=|d284b4e655b8db07949cb8ddb16b303e1563d79d4dcb0c97712a626fce86161e"; username-localhost-8875="2|1:0|10:1588245126|23:username-localhost-8875|44:NmM0YWY1ZDcxYTA3NDljN2FiYzhiNTc1MjQ5ODg2MjY=|427a6cb38c63a1741e606896fe5a580afd59c1ff87abf9a4e0264490873c17e2"; username-localhost-8860="2|1:0|10:1588250619|23:username-localhost-8860|44:OTExMGQyNDNjMjBhNGM5ODg1YWQ2NDJlNzRjMzllMzk=|2d821eccb6f9ec968dea68c156df9905faa58542fa476b22aea7d3e12ab9d688"; username-localhost-8896="2|1:0|10:1588346410|23:username-localhost-8896|44:MzU1YjRiODYwMGQ1NGQxOWEwYzZmMGFhNmZmOTdiMDU=|93f109a79e3afb279189839dd339498c63b1aea3f9efa323e1a78f7ff52a5d13"; username-localhost-8888="2|1:0|10:1588875227|23:username-localhost-8888|44:MjMxNTQwYTA4NWY4NGNiZDk1YmVkM2I4N2ExMTNmM2E=|9171347b87457f54f46192df346a98d8e3059931b3ad63077f4b6a3237503a97"


[2020-05-13T15:31:25.784][ERR][messagelogger/message/Companion] JSONParser reported errors. 
illegal value
[2020-05-13T15:31:25.788][INFO][companionServer/onTerminateConnection] socket scheduled to be deleted
```

Seems like a "Connection-Keep-alive" Issue.
You can use Firefox browser, for now, sometimes chrome does not send the data correctly. With Firefox it will always work. You can confirm that for us too.


@ouuan  A possible solution for this issue is to look for a QtHttpServer library, but I could not find any good library for Http in Qt, We can remove that TcpSocket based implementation with a library server.

**Comment by ouuan** [comment] 2020-05-13 12:12
> added duplicate

This is reported before, but that was closed, and I think there's no other open issue with the same topic?

> A possible solution for this issue is to look for a QtHttpServer library, but I could not find any good library for Http in Qt, We can remove that TcpSocket based implementation with a library server.

Just did a quick search and found [QHttp](https://github.com/azadkuh/qhttp).

**Comment by ouuan** [comment] 2020-05-14 14:02
[QHttp](https://github.com/cpeditor/qhttp) is poorly documented, we may have a tough time if we want to use it :thinking: Also, it's hard to determine whether this bug is fixed or not, because it doesn't always happen.

So I'll mark this of low priority until someone is willing to work on it (either to use QHttp or other better solutions).

**Closed** 2020-10-08 17:33 UTC
Labels: bug, can't reproduce, low_priority
