### ISSUE TITLE
Use GDB to Debug

### ISSUE THREAD

**Issue by devsong42** [cpeditor/cpeditor#1106] opened 2022-10-02 06:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

Sometimes I need to use GDB to debug my code, but CP Editor don't have it! 

### Describe the feature you'd like

Add Debug using GDB. 

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment] 2022-10-02 07:22
Duplicate of #17.

However, you can use the "reveal executable file" option in the context menu of the tabs to manually run gdb (or other gdb frontends), if GUI is not a must.

**Closed by ouuan** 2022-10-02 07:22 UTC
Labels: enhancement
