### ISSUE TITLE
Commented curly braces will be matched.

### ISSUE THREAD

**Issue by Jonathan523** [cpeditor/cpeditor#1230] opened 2023-10-08 09:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the code is
```
int main(){
//while(something){
while(something){
    do something;
    }
}
```
than the curly brace commented (on line 2) will be matched with the curly brace on line 6
![image](https://github.com/cpeditor/cpeditor/assets/121601701/0e851c41-9f53-40ec-b2fa-6748eff5c83f)

### Expected Behavior

Commented curly braces shouldn't be matched.
For the previous example, the curly brace on line 6 should match the curly brace on line 1

### Steps To Reproduce

1. Create a file
2. Fill in the following code
```
int main(){
//while(something){
while(something){
    do something;
    }
}
```
3. Click the last line(right to the curly brace

### CP Editor Version

6.10.3

### OS

Windows 11

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment] 2023-10-08 10:18
Duplicate of #556

**Closed by ouuan** 2023-10-08 10:18 UTC
Labels: bug
