### ISSUE TITLE
Display simple completion or suggestion

### ISSUE THREAD

**Issue by FxBdelay** [cpeditor/cpeditor#1153] opened 2023-03-10 08:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

![image](https://user-images.githubusercontent.com/49864633/224261689-a4ccdfc0-0ed7-4035-8db8-637256483b14.png)
I found that [https://github.com/cpeditor/lsp-cpp](url)  offers completion, but I can't get the message of completion besides error.

### Describe the feature you'd like

display the message of completion, just like "Maybe you are mean iostream" but not "file not found"

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment] 2023-03-10 09:14
Duplicate of #156

**Closed by ouuan** 2023-03-10 09:14 UTC
Labels: enhancement
