### ISSUE TITLE
program compare support

### ISSUE THREAD

**Issue by StudyingFather** [cpeditor/cpeditor#205] opened 2020-03-15 04:09 UTC
**Is your feature request related to a problem? Please describe.**

Sometimes we write two programs for a problem, and we need to check them by compare their output.

Maybe it can be done automatically.

**Describe the solution you'd like**

Get input from generator, run programs, and compare their output automatically.

**Describe alternatives you've considered**

**Additional context**

**Comment by ouuan** [comment] 2020-03-15 04:17
Duplicate of #162.

**Closed by ouuan** 2020-03-15 04:17 UTC
Labels: enhancement
