### ISSUE TITLE
Support non-monospace code editor fonts

### ISSUE THREAD

**Issue by Ravenclaw-OIer** [cpeditor/cpeditor#558] opened 2020-08-11 15:47 UTC
**Is your feature request related to a problem? Please describe.**

Sometimes a font is not exactly monospace or not marked as monospace, but it *is* comfortable. (For example [Fira Code](https://github.com/tonsky/FiraCode/) here).

We cannot choose them as an editor font because they are not marked monospace.

**Describe the solution you'd like**

Add an option to display all fonts in the editor font chooser.

**Describe alternatives you've considered**

Display all fonts, but mark those explicitly marked as monospace with some specific flags (boldface for example)

This is how Visual Studio did.

**Additional context**

**Comment by ouuan** [comment] 2020-08-11 15:49
Duplicate of #217.

**Closed by ouuan** 2020-08-11 15:49 UTC
Labels: enhancement
