### ISSUE TITLE
Do not parse comments in strings

### ISSUE THREAD

**Issue by testitem** [cpeditor/cpeditor#396] opened 2020-06-10 01:22 UTC
**Is your feature request related to a problem? Please describe.**

`string k = "//";`
The ending `//";` It's not supposed to be formatted like a comment.

**Describe the solution you'd like**

Don't render comments when the start is in a string literal.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ouuan** [comment] 2020-06-10 01:29
Duplicate of #174

**Closed** 2020-06-10 01:29 UTC
Labels: duplicate, enhancement
