### ISSUE TITLE
Filename when saving needs to match the full problem name

### ISSUE THREAD

**Issue by rahiid007** [cpeditor/cpeditor#1243] opened 2023-10-22 11:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

when I open a problem from OJ the file name is initially A. But, It would had been better if the name use the full name of  the problem. In vscode the file name is defaulted to the problem name, but here I need to rename every time I open a new problem.

![image](https://github.com/cpeditor/cpeditor/assets/45300686/9f65036f-4dc3-47f8-bf0b-eca822c50c7a)

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment] 2023-10-22 11:37
Duplicate of #580 and #964.

**Closed by ouuan** 2023-10-22 11:37 UTC
Labels: enhancement
