### ISSUE TITLE
Please add code-autocomplete base on word

### ISSUE THREAD

**Issue by fjy666** [cpeditor/cpeditor#1113] opened 2022-11-15 05:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

No auto-complete makes my coding very slow. 

### Describe the feature you'd like

Please add word-autocompletion because it`s simple to implement and it can boost coding speed. We can keep a keyword list in our commets.  
(Just like default VSCode and Sublime Text)  
And it will be even greater to sort by time of use!

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment] 2022-11-15 05:24
Duplicate of #156. (I guess you are not specifically requesting an auto-completion that supports only the keywords, without variable/function names, etc. IMO that would not be very helpful.)

**Closed by ouuan** 2022-11-15 05:24 UTC
Labels: enhancement
