### ISSUE TITLE
Keybinding

### ISSUE THREAD

**Issue by Xelewet** [cpeditor/cpeditor#1226] opened 2023-10-07 03:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I want more keybinding

### Describe the feature you'd like

I would like to CTRL+L, CTRL+D, and etc

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment] 2023-10-07 04:01
Duplicate of #214. And I don't know what you mean by <kbd>Ctrl+L</kbd> and <kbd>Ctrl+D</kbd>.

**Closed by ouuan** 2023-10-07 04:01 UTC
Labels: enhancement

**Comment by ouuan** [comment] 2023-10-07 04:05
Well, #1182 was opened by you... And this time you provided even less information.

**Comment by ouuan** [comment] 2023-10-07 04:07
Please stop opening duplicate issues.
