### ISSUE TITLE
Themes for the IO part

### ISSUE THREAD

**Issue by tb148** [cpeditor/cpeditor#379] opened 2020-05-30 05:28 UTC
**Is your feature request related to a problem? Please describe.**

The IO part is always white even if the theme is dark. But some CP (like me) might want it to also be dark.

**Describe the solution you'd like**

Also change the look of the IO part when changing the theme.

**Describe alternatives you've considered**

Maybe selecting different themes for the editor part and the IO part?

**Additional context**

![图片](https://user-images.githubusercontent.com/28220642/83320364-5213e700-a279-11ea-8db0-08894a858554.png)

**Comment by ouuan** [comment] 2020-05-30 05:29
Duplicate of #265.

**Closed by ouuan** 2020-05-30 05:29 UTC
Labels: duplicate, enhancement
