### ISSUE TITLE
Message logger font automatically resets.

### ISSUE THREAD

**Issue by AchintyaK20** [cpeditor/cpeditor#604] opened 2020-09-21 20:03 UTC
**Describe the bug**
After applying the message logger font, it stays applied only till cpeditor is open. When closing and reopening cpeditor, the message logger font shows an unknown font and unknown font size. Basically it resets my applied font to some other font on every launch. However in the settings it shows the correct name of the font which I had applied. And because of that I've to set the message logger font everytime.

**To Reproduce**
Set the UI style as auto/light/dark fusion and the message logger font to some distinguishable font. Then relaunch cpeditor and run a sample program.

**Screenshots**
After setting the message logger font-

![Screenshot (73)](https://user-images.githubusercontent.com/56220374/93815748-195aac00-fc74-11ea-82f6-77ed3f161e1f.png)

After closing and relaunching cpeditor-

![Screenshot (74)](https://user-images.githubusercontent.com/56220374/93815784-2a0b2200-fc74-11ea-87ea-d1adcc35e546.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: 6.64/6.5 (Tried on both)

**Additional context**
None

**Comment by coder3101** [comment] 2020-09-22 10:15
@all-contributors add @AchintyaK20 for bugs

**Comment by coder3101** [comment] 2020-09-22 10:18
Steps to reproduce:
- Set Light/Dark Fusion Style
- Change MessageLogger Font
- Exit Application
- Launch Application
- Check the MessageLogger font has changed to default System Font while it in Settings the correct font is present.

**Comment by coder3101** [comment] 2020-09-22 10:49
This issue is caused because a UI Style is applied after the other Appearance Settings are applied. Due to this in some cases, the applied settings are replaced by UI Style properties like fonts.

This only has effects for stuff that are created in ui.xml. It explains why no such issue exists for other QPlainTextEdit's like Testcase or Code Editor because they are created after UI settings are applied.


A solution is to delay the `applySettings()` in the constructor of mainwindow.cpp by using SingleShot Timer. In order to be on safe side, We can also make `appwindow` apply `mainwindow` settings only after it has applied its own settings.

**Comment by coder3101** [comment] 2020-09-22 11:11
This has been fixed and will be released in 6.7.

Thanks for pointing this out!

**Comment by AchintyaK20** [comment] 2020-09-22 15:29
My Pleasure! Anything to improve my favourite text editor!

**Closed** 2020-09-25 11:46 UTC
Labels: bug, high_priority
