### ISSUE TITLE
Doesn't work properly with retina display on macOS 10.15.3

### ISSUE THREAD

**Issue by WZKSDN** [cpeditor/cpeditor#225] opened 2020-04-06 05:24 UTC
**Describe the bug**

The resolution is low on my MacBook with a retina display.

**To Reproduce**

Double click to open the editor.

**Screenshots**

<img width="877" alt="截屏2020-04-06下午1 19 14" src="https://user-images.githubusercontent.com/14256391/78525441-b9796180-7809-11ea-8960-7a437ff68438.png">

**Environment**

 - OS: [macOS 10.15.3]
 - CP Editor Version: [6.1.5]

**Comment by ouuan** [comment] 2020-04-06 05:29
Duplicate of #197.

I have no idea how to fix this up to now. I've Googled for this but no solution works.

**Comment by coder3101** [comment] 2020-04-06 05:31
Let me reopen this issue. Experiment something with his MacBook Pro Retina.

**Comment by ouuan** [comment] 2020-04-06 05:32
> Experiment something with his MacBook Pro Retina.

What do you mean?

**Comment by coder3101** [comment] 2020-04-06 05:33
Can you please add :

following lines under the <dict> tag:
```
        <key>NSPrincipalClass</key>
        <string>NSApplication</string>
        <key>NSHighResolutionCapable</key>
        <true/>
```

Inside info.plist inside CPEditor.app bundle! Open the bundle with Finder and then navigate to Contents/Resources/Info.plist (Or something similar find it)

**Comment by WZKSDN** [comment] 2020-04-06 06:16
@coder3101 Problem Solved. Probably you could modify the release then.

**Comment by ouuan** [comment] 2020-04-06 06:19
@coder3101 Are there any other ways except modify `info.plist` when making releases? It says "CMake only supports setting a limited number of properties that affect the Info.plist template" [here](https://stackoverflow.com/questions/42313808/customising-macos-bundles-info-plist-file-with-cmake).

**Comment by coder3101** [comment] 2020-04-06 06:21
Don't close the issue unless we have integrated this change to our code base. 

> Are there any other ways except modify info.plist when making releases?

I don't know yet and indeed I see Cmake doesn't provide this property. So how should we add it?

**Comment by ouuan** [comment] 2020-04-06 06:23
We can add this in the CI scripts, but if users compile from source, they have to add it manually.

**Comment by coder3101** [comment] 2020-04-06 06:27
> By default its Info.plist file is created by configuring a template called MacOSXBundleInfo.plist.in located in the CMAKE_MODULE_PATH

See https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_BUNDLE_INFO_PLIST.html

No need for script, maybe we can just modify that `MacOSXBundleInfo.plist.in` file in CMake Module. It says that this plist is used as template and then you can only change few keys, so how about we change the template itself to include the above lines?

**Comment by ouuan** [comment] 2020-04-06 06:30
> so how about we change the template itself to include the above lines?

If it works, of course we should.

**Comment by coder3101** [comment] 2020-04-06 06:30
> We can add this in the CI scripts, but if users compile from source, they have to add it manually.

Or better we instruct CMake to run that Script. User will also compile from CMake. But I still think there should be a way for choosing the default Bundle template which will be better.

**Comment by ouuan** [comment] 2020-04-06 06:32
I don't want to work on anything specifically related to macOS. I'll completely leave this for @coder3101.

**Closed** 2020-04-08 17:35 UTC
Labels: bug, high_priority, macOs

**Comment by ouuan** [comment] 2020-05-03 03:03
@allcontributors add @WZKSDN as a contributor for bug report.
