### ISSUE TITLE
[Request] Support for VIM key bindings and for use of ALT to move line

### ISSUE THREAD

**Issue by yashgosa** [cpeditor/cpeditor#1303] opened 2024-02-09 19:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

1. Whenever I am coding sometimes I accedently press CTRL and it leads to font size being decreased
2. Unable to use ALT to move line
3.  Unable to customize theme of editor

### Describe the feature you'd like

Support for use of ALT to move line as well as support copy and paste of line without selection. I would love to contribute to this project like adding XML file for themes or enabling programmers to write scripts for theme (like in vim) and adding support for use of ALT to move line, if someone could guide me.

### Describe alternatives you've considered

If theme customization is not possible then we can atleast add new themes or let user configure them like in VIM. Thank you!

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment] 2024-02-10 02:26
There are <kbd>Ctrl+Shift+Up/Down</kbd> to move lines, so I think this is duplicate of #214.

Vim mode is #220.

Many more themes are already available on the master branch with KSyntaxHighlighting. There is also #595.

And, even if they are not duplicate, please don't mix multiple requests in a single issue.

**Closed by ouuan** 2024-02-10 02:26 UTC
Labels: enhancement
