### ISSUE TITLE
Add vim features to this editor.

### ISSUE THREAD

**Issue by TayTTo** [cpeditor/cpeditor#1409] opened 2024-09-30 15:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I'm vim user and I love it, I also love th CP editor too. But I don't want to put too many things to the vimrc file, I want I can solve coding puzzle any time just open the CP editor.

### Describe the feature you'd like

Hope you can add vim features like vim movements, visual mode, normal mode, etc ....

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment] 2024-09-30 15:39
duplicate of #220

**Closed by ouuan** 2024-09-30 15:39 UTC
Labels: enhancement
