### ISSUE TITLE
Seperate JSON file for settings

### ISSUE THREAD

**Issue by Techietal** [cpeditor/cpeditor#1386] opened 2024-07-22 07:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I actually customize all the IDEs I have used very much. One thing that literally irritates me in cp editor is that I cannot add customize line spacing

### Describe the feature you'd like

If you can include a JSON type file for CP editor too then that would be really crazy as we can choose the way we want. Otherwise I request you to add line spacing or line padding feature in further updates.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment] 2024-07-22 12:47
You are mixing two requests "JSON config file format" and "line spacing setting" in a single issue, so I'm not sure about what you actually want.

The line spacing setting seems like a duplicate of #1062.

We will not use JSON for the config file. I'm not sure if you are aware that there is already a config file in INI format. We may consider using YAML instead. However, we recommend changing the settings via GUI instead of directly modifying the config file.

**Closed by ouuan** 2024-07-22 12:47 UTC
Labels: enhancement

**Comment by Techietal** [comment] 2024-07-22 12:56
Hey developer. Hope you are pink. When you gonna add the option for line
spacing?
