### ISSUE TITLE
Feature Request for auto complete

### ISSUE THREAD

**Issue by deepkamalsingh** [cpeditor/cpeditor#879] opened 2021-06-17 10:56 UTC
**Is your feature request related to a problem? Please describe.**

Hi, I really like using cp editor but could you please add auto complete feature so that I dont have to type long variable names again and again. Thank you.

**Describe the solution you'd like**

It would be nice if it stores all the variables which are  declared by the user and display them accordingly, It could be similar to the one used by vs code etc.

**Describe alternatives you've considered**

Till then I will keep typing them by hand.

**Additional context**

**Comment by ouuan** [comment] 2021-06-17 11:22
Duplicate of #156.

**Closed by ouuan** 2021-06-17 11:22 UTC
Labels: enhancement
