### ISSUE TITLE
The displayed size of the default font is not the same as the actual size of the default font

### ISSUE THREAD

**Issue by sonulohani** [cpeditor/cpeditor#425] opened 2020-06-20 06:40 UTC
**Describe the bug**

Open cpeditor for the first time with settings removed and you will see the font size is very small than what is set as default. Close and again reopen and this time you will see correct font size.

**To Reproduce**
1. Remove **cp_editor_settings.ini** from "C:\Users\<username>\AppData\Local\CP Editor" if exists.
2. Open cpeditor

Expected behavior: The default font size is set to 12 and is what expected to show in editor and other places.
Actual behavior: Font size is small (Somewhat near to 6 or 7 pt)

**Screenshots**

**First time**

![image](https://user-images.githubusercontent.com/2958681/85195320-f922f600-b2ee-11ea-8b8e-da71ccd05e96.png)

**Second time** 

![image](https://user-images.githubusercontent.com/2958681/85195333-0d66f300-b2ef-11ea-84db-faddf4ba6c5a.png)

**Environment**

 - OS: Windows 10
 - CP Editor Version: Latest master

**Comment by coder3101** [comment] 2020-06-20 06:49
The second time you launch, it actually writes the `monospace 12` by Generating Settings File.

The first time, it uses the settings.json `default: <text>` to create the Font. It could be that no size of the font is set for `default: <font>`

**Comment by ouuan** [comment] 2020-06-20 07:00
I guess this is caused by #422?

**Comment by ouuan** [comment] 2020-06-20 07:44
I think this is actually a duplicate of #422.

**Comment by ouuan** [comment] 2020-06-20 08:31
I can confirm that on my Arch Linux with KDE, when resetting to default, the font is actually in the size of the system font, and I think that's probably a bug of Qt. We can fix it by explicitly setting a size for the default font.

And the bug should be "the displayed size of the default font is not the same as the actual size of the default font".

**Comment by ouuan** [comment] 2020-06-20 08:38
![image](https://user-images.githubusercontent.com/30581822/85197575-79a81d80-b314-11ea-96e5-e88a6c32033d.png)

A minimal reproduce outside of CP Editor.

**Comment by ouuan** [comment] 2020-06-20 08:45
I did a quick search in [Qt Bug Tracker](https://bugreports.qt.io/projects/QTBUG/issues) and didn't find this. Maybe I can open an issue there :thinking:

**Comment by ouuan** [comment] 2020-06-20 09:18
Opened [here](https://bugreports.qt.io/browse/QTBUG-85159).

**Comment by sonulohani** [comment] 2020-06-20 09:19
For now I have pushed the temporary fix. Please have a look.

**Closed** 2020-06-20 10:38 UTC
Labels: bug
