### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by dipeshyadav331** [cpeditor/cpeditor#1280] opened 2023-12-28 13:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

Please give the support for kotlin language along with java python and cpp

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment] 2023-12-28 13:44
Duplicate of #371 (we would not specifically support Kotlin without #371)

**Closed by ouuan** 2023-12-28 13:44 UTC
Labels: enhancement
