### ISSUE TITLE
Making cp editor more awesome

### ISSUE THREAD

**Issue by deependujha** [cpeditor/cpeditor#1028] opened 2021-12-18 14:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

I do not remember all the functions and syntaxes. I generally use VS Code for cp. Now, I've shifted to cp editor. It is awesome. But, I can't use it for contests, as I don't remember much of syntaxes.

### Describe the feature you'd like

Can we guys please have IntelliSense support? It will really make it awesome. 

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [X] I'd like to have a try (with the help of the maintainers)
- [ ] No, thanks

**Comment by ouuan** [comment] 2021-12-19 01:22
Duplicate of #156

**Closed by ouuan** 2021-12-19 01:22 UTC
Labels: enhancement
