### ISSUE TITLE
adding emet and auto indentation after saving code 

### ISSUE THREAD

**Issue by Rrdesh07** [cpeditor/cpeditor#1199] opened 2023-08-17 10:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

actually i have to write whole syntax and indent by myself it becomes irrtating while writing big code 

### Describe the feature you'd like

actually add the emet like in vscode for auto complete code which can save a lot of time and some extensions like auto indention after saving the code 

### Describe alternatives you've considered

no

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

no

**Comment by ouuan** [comment] 2023-08-17 10:49
The auto-complete part is a duplicate of #156.

You may want to set up clang-format and enable format code on save in CP Editor.

**Closed by ouuan** 2023-08-17 10:49 UTC
Labels: enhancement
