### ISSUE TITLE
In Windows machine its saying unknown publisher.

### ISSUE THREAD

**Issue by veeru004** [cpeditor/cpeditor#1053] opened 2022-02-20 18:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/40502450/154857117-a3ad46f2-afb0-4997-b1be-e7d7d7572436.png)
if source is in github then its kinda secured app right? why machine is showing like that. do i have to worru about this?

### Expected Behavior

---

### Steps To Reproduce

---

### CP Editor Version

6.9.4

### OS

Windows

### Are you willing to contribute to this?

- [ ] I'm ready to fix this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by swift-zym** [comment] 2022-02-20 22:33
Duplicate of #1049

**Closed** 2022-02-20 22:33 UTC
Labels: bug
