### ISSUE TITLE
Bundle cf-tools with cp-editor

### ISSUE THREAD

**Issue by duttaditya18** [cpeditor/cpeditor#91] opened 2020-01-11 12:44 UTC
**Is your feature request related to a problem? Please describe.**
Installing **[cf-tools](https://github.com/xalanq/cf-tool)** is a long and painful process especially setting up templates.

**Describe the solution you'd like**
Have cf-tools bundled with cp-editor and have a GUI for logging in and setting up templates.

**Describe alternatives you've considered**
Setting up cf-tools the normal way.

**Comment by coder3101** [comment] 2020-01-11 14:33
Yes it indeed is a big process but you have to do it once only. I will look into packaging CF tool inside editor but to login and setup one needs to interactively do it. If i modify CF tools that GUI is also possible. But first as of now, i have to enhance the code editor. Rest assured when i find time, i will do it too.

**Comment by coder3101** [comment] 2020-03-25 10:14
Closed as duplicate of #142

**Closed by coder3101** 2020-03-25 10:14 UTC
Labels: enhancement, low_priority, preferences
