### ISSUE TITLE
代码移动

### ISSUE THREAD

**Issue by lwqmouo** [cpeditor/cpeditor#1206] opened 2023-09-06 23:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### Describe the feature you'd like

我希望在我选中一段代码时，可以将它们拖动到整个代码的其他部分

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment] 2023-09-07 02:09
Duplicate of #985.

**Closed by ouuan** 2023-09-07 02:09 UTC
Labels: enhancement
