### ISSUE TITLE
关于一些功能的引进

### ISSUE THREAD

**Issue by zzzwwh** [cpeditor/cpeditor#1415] opened 2024-11-29 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

可以添加一个代码补全的功能

### Describe the feature you'd like

no

### Describe alternatives you've considered

no

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

### Anything else?

no

**Comment by ouuan** [comment] 2024-11-29 14:44
duplicate of #156 

请不要用中文开 issue，可以在 https://github.com/cpeditor/cpeditor-cn/ 提问

**Closed by ouuan** 2024-11-29 14:44 UTC
Labels: enhancement
