### ISSUE TITLE
Add Some Visual Features and Extensions

### ISSUE THREAD

**Issue by rifatr** [cpeditor/cpeditor#854] opened 2021-06-05 06:18 UTC
1. Add some theme more.
2. Add more settings like change spacing for TAB key.
3. In testcase section, add Check All or Uncheck All buttons.
4. It's important. Add a nice "Auto Complete" and "Code Formatting" extensions. Current there are no "Auto Complete" extension and clang formatting is annoying.

**Comment by ouuan** [comment] 2021-06-05 08:46
>     1. Add some theme more.

We'll add all of https://github.com/KDE/syntax-highlighting/tree/master/data/themes in the future.

>     2. Add more settings like change spacing for TAB key.

https://cpeditor.org/docs/preferences/code-edit/#tab-width

>     3. In testcase section, add Check All or Uncheck All buttons.

![screenshot](https://user-images.githubusercontent.com/30581822/120885705-da5f6180-c61c-11eb-8138-77f6eff28e20.png)

>     4. It's important. Add a nice "Auto Complete"

Duplicate of #156.

>     clang formatting is annoying

What formatter do you want? Have you checked https://clang.llvm.org/docs/ClangFormatStyleOptions.html to choose the style you want?

---

I'll close this because this is not a valid issue. You didn't fill in the issue template. Some features exist but you didn't notice them.

If you want to have further discussions on these feature requests, please open a new issue with the issue template filled. If you have questions, please ask in [Dicussions](https://github.com/cpeditor/discussions) instead of opening an issue.

**Closed by ouuan** 2021-06-05 08:46 UTC
Labels: enhancement
