### ISSUE TITLE
Combinations

### ISSUE THREAD

**Issue by Xelewet** [cpeditor/cpeditor#1174] opened 2023-06-07 17:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

It is not enough of combinations (Like ctrl + L, and etc.)

### Describe the feature you'd like

I would like to use CTRL+SHIFT+BACKSPACE to delete whole line. And combination to find all dedicated variables and change them

### Describe alternatives you've considered

Just add them

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment] 2023-06-08 00:08
There are <kbd>Ctrl+Shift+K</kbd> and <kbd>Ctrl+F</kbd>. Otherwise it's duplicate of #214.

**Closed by ouuan** 2023-06-08 00:08 UTC
Labels: enhancement
