### ISSUE TITLE
Incorrect hot exit when there are multiple windows

### ISSUE THREAD

**Issue by ouuan** [cpeditor/cpeditor#131] opened 2020-01-29 11:14 UTC
**Describe the bug**

If you open multiple windows using the `--new` command-line option, the new window will load the tab status which is already loaded by the previously opened window. If you close one of them, it will save the tab status, which may be covered by another window later.

**To Reproduce**

(Suppose there is no tab in the last session.)
1. Open a window.
2. Open a tab in this window. Write "foo" in it.
3. Close this window.
4. Open a new window. Now you will see a tab with "foo" in it.
5. Open another window (`CPEditor --new` in the command line). Now you will see another window with a tab with "foo" in it.
6. Change "foo" into "bar" in the first window, and close it.
7. Open another window, there will be "bar" in it.
8. Close the window opened in step 4.
9. Open another window, there will be "foo" in it.

**Expected behavior**

Sublime Text provides a good example of how to behave correctly with multiple windows and hot exit: don't load tab status if there is another window running (an alternative is to clear the tab status after loading it); acts like hot exit is disabled if there are multiple windows opened.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - Version: It happens on every version after hot exit was introduced. (No need to use `--new` before single application was introduced.)

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by ouuan** [comment] 2020-01-30 03:04
This should be easy to implement after itay-grudev/SingleApplication#90 is merged, and it's not so critical because `--new` is not frequently used, so I decide to make it an issue for new contributors, here's the instruction:

The hot exit is load and saved in `src/appwindow.cpp`, so you should edit this file. Every time when checking whether hot exit is enabled (`settingManager->isUseHotExit()`), check if the current instance is the only running instance, too. You have to use the `SingleApplication::numberOfInstances()` function. To get the pointer to the SingleApplication, use `static_cast<SingleApplication *>(QApplication::instance())`.

**Comment by ouuan** [comment] 2020-01-31 14:06
The SingleApplication function is not that easy, it may need time to wait for `SingleApplication::getNumberOfInstances()` to be ready.

**Comment by coder3101** [comment] 2020-02-20 15:37
If this depends on some other library to be fixed. It should not be in 6.0 milestone. We don't have when will library author fix it and we have to wait for him.

**Comment by ouuan** [comment] 2020-02-20 15:44
Maybe we need to fix it via a PR if he won't fix this.

**Comment by coder3101** [comment] 2020-02-20 15:50
@ouuan I saw your conversations and he said his timings are packed and it would take him time. If you think it's a small implementation you could propose a PR or maybe wait for him to fix it. As you feel okay, you could do it that way!

**Comment by ouuan** [comment] 2020-02-20 15:52
I think it's not very easy to fix, but it's important because it may cause file loss. Though not many people use the `--new` feature.

**Comment by coder3101** [comment] 2020-02-20 16:00
@ouuan It has been over 15 days and no progress on the issue you opened in his repository. I do understand that this involves communication via sockets and all, so for sure it's hard, I think instead of diverting our attention to improve dependency, we could improve our editor. I also know that except for some Linux and Super cmd loving guys, people hardly use editor from cmd. However to solve this maybe you could issue a warning (on cmd) when --new is called stating why not to use this flag while launching editor, unless he the issue is fixed.

Or let me guess, --new can cause hotexit to fail because hot exit can only keep one app status. Is that the issue?

**Comment by ouuan** [comment] 2020-02-20 16:04
> Or let me guess, --new can cause hotexit to fail because hot exit can only keep one app status. Is that the issue?

That's true. I've described the issue clearly, what are you guessing?

**Comment by coder3101** [comment] 2020-02-20 16:20
@ouuan I assume that Qsettings commit transactions are atomic in nature. Which it should be since all DB should have Atomic Property.

 If QSetting is atomic, before a new secondary instance we can keep in settings a key "instance_count", initially set to 0, as primary/secondary instance launches, we will increment this. When hotexit is triggered it would check this key if it is 1, it will performHotexit otherwise it will not because this current instance is secondary or as you want hotExit to behave. Also, as soon as instance is killed, in its destruction it will decrement that value. If however a instance was crashed and failed to decrement, you might have that value set to non zero when all instances are killed, we might have to do something.

If Atomic property holds, there should be no any race conditions. Its more like a hack and could suffice getInstanceCount() for the time. It isn't fixed in the library

**Comment by ouuan** [comment] 2020-02-21 04:29
> If however a instance was crashed and failed to decrement, you might have that value set to non zero when all instances are killed, we might have to do something.

That's the problem. I have better solutions if don't need to consider crashes.

**Comment by ouuan** [comment] 2020-02-21 15:21
I think the best solution as for now is to disable the `--new` option.

**Comment by coder3101** [comment] 2020-02-21 15:24
@ouuan Agreed. When library fixes it's issue, we will re enable it again

**Closed** 2021-02-27 13:12 UTC
Labels: awaiting on dependency, bug, low_priority
