### ISSUE TITLE
Bug about Syntax Highlighter in C++ language

### ISSUE THREAD

**Issue by GitPinkRabbit** [cpeditor/cpeditor#869] opened 2021-06-11 11:50 UTC
**Describe the bug**

cannot properly display string literal with pseudo-multiline comment inside

**To Reproduce**

`"/*\n*/"`

**Additional context**

referring <https://www.luogu.com.cn/discuss/show/321572>

**Comment by ouuan** [comment] 2021-06-11 11:53
Duplicate of #174.

**Closed by ouuan** 2021-06-11 11:53 UTC
Labels: bug
