### ISSUE TITLE
Python tabulation

### ISSUE THREAD

**Issue by George1685** [cpeditor/cpeditor#1107] opened 2022-10-05 03:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is this feature provided in the master branch?

- [X] I have checked the changelog

### The problem you are facing

in Python, yo_u ca**nnot creat**e tab ju_mp _out with ":**",  what i**s needed for_ go_od_ formatting.

> **pliz_z a**dd it._

### Describe the feature you'd like

If Python formatting will be added in release.

### Describe alternatives you've considered

If Python formatting will be added in open beta release.

### Are you willing to contribute to this?

- [ ] I'm ready to contribute to this (and will open a PR soon)
- [ ] I'd like to have a try (with the help of the maintainers)
- [X] No, thanks

**Comment by ouuan** [comment] 2022-10-05 03:43
> in Python, yo_u ca**nnot creat**e tab ju_mp _out with ":**", what i**s needed for_ go_od_ formatting.

I don't quite understand this sentence, but I guess it's a duplicate of #548.

**Closed by ouuan** 2022-10-05 03:43 UTC
Labels: enhancement
